export {
  SimulacrumClient,
  SimulacrumApiError,
  createSimulacrumClient,
  type SimulacrumClientOptions,
  type RegisterAgentInput,
  type RegisterAgentResponse,
  type ChallengeResponse,
  type LoginInput,
  type LoginResponse,
  type AgentInfo,
  type Market,
  type CreateMarketInput,
  type PlaceBetInput,
  type PlaceOrderInput,
  type ResolveMarketInput,
  type SelfAttestInput,
  type ChallengeResolutionInput,
  type OracleVoteInput,
  type ClaimWinningsInput,
  type WalletBalance,
  type FaucetResponse,
  type OrderBook,
  type OrderBookEntry,
  type BetSummary
} from "./client.js";
