// Re-export all shared types from the canonical @simulacrum/types package.
// This file exists so that existing imports within the UI continue to work.
export type {
  Agent,
  AgentMode,
  AutonomyStatus,
  ClaimRecord,
  ClawdbotGoal,
  ClawdbotGoalStatus,
  ClawdbotMessage,
  ClawdbotNetworkStatus,
  ClawdbotProfile,
  InsurancePolicy,
  InsurancePool,
  Market,
  MarketBet,
  MarketBetsSnapshot,
  MarketChallenge,
  MarketOracleVote,
  MarketOrder,
  MarketResolution,
  MarketStatus,
  MarketSelfAttestation,
  OrderBookSnapshot,
  OrderSide,
  PolicyStatus,
  ReputationLeaderboardEntry,
  TrustEdge,
  TrustGraph,
  WsEvent,
} from '@simulacrum/types'
